- name: SDN A2
  hosts: routers
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Modify Router Banner
      ios_config:
        lines:
          - banner motd ^ Router {{ inventory_hostname }} ^

    - name: Backup Running Config #This is the backup runnign config being stored in /backups
      ios_config:
        backup: yes
        backup_options:
          filename: "running-config-{{ inventory_hostname }}" 
          dir_path: "ansible/backups"
